# Generated by Django 4.2.4 on 2023-08-12 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('HEALERS', 'Хилы'), ('VENDORS', 'Торговцы'), ('SKINNERS', 'Кожевники'), ('DD', 'ДД'), ('POTION_MASTERS', 'Зельевары'), ('TANKS', 'Танки'), ('QUEST_GIVERS', 'Квестгиверы'), ('GUILD_MATERS', 'Гилдмастеры'), ('SPELL_MASTERS', 'Мастера заклинаний'), ('BLACKSMITHS', 'Кузнецы')], default='Tanks', max_length=28, verbose_name='category')),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('text', models.TextField(default='Введите текст объявления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
        ),
        migrations.CreateModel(
            name='Coment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.post')),
            ],
        ),
    ]
