# Generated by Django 4.2.4 on 2023-08-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('QUEST_GIVERS', 'Квестгиверы'), ('VENDORS', 'Торговцы'), ('SKINNERS', 'Кожевники'), ('HEALERS', 'Хилы'), ('POTION_MASTERS', 'Зельевары'), ('TANKS', 'Танки'), ('DD', 'ДД'), ('SPELL_MASTERS', 'Мастера заклинаний'), ('BLACKSMITHS', 'Кузнецы'), ('GUILD_MATERS', 'Гилдмастеры')], default='Tanks', max_length=28, verbose_name='category'),
        ),
    ]
